# finite_element_package_1d
include("mesh1d.jl")
include("fem1d.jl")
include("shaperef1d.jl")
include("shapeloc1d.jl")
include("quadref1d.jl")
include("quadloc1d.jl")
include("evalfe1d.jl")
include("errorloc1d.jl")
include("errorglob1d.jl")
include("linformloc1d.jl")
include("linformglob1d.jl")
include("biformloc1d.jl")
include("biformglob1d.jl")
include("boundaryclassify1d.jl")
